In [ ]:
import numpy as np
from unittest import TestCase
import math
import pickle as pk

In [ ]:

datapath = '/content/drive/My Drive/Especializacion UBA/Introduccion a IA/data/'

# Data set up

In [ ]:
!unzip '/content/drive/My Drive/Especializacion UBA/Introduccion a IA/data/kaggle_movie_ratings.zip' -d '/content/drive/My Drive/Especializacion UBA/Introduccion a IA/data/'

Archive:  /content/drive/My Drive/Especializacion UBA/Introduccion a IA/data/kaggle_movie_ratings.zip
  inflating: /content/drive/My Drive/Especializacion UBA/Introduccion a IA/data/ratings.csv  


# Ejercicio 1

In [ ]:
a = np.array([[1,-1,1],[-3,4,5]],np.float64)

In [ ]:
class NormTestClass(TestCase):
  def __init__(self):
    self.tester1 = np.array([[1,2,3,4,5,0],[0,0,0,4,0,8]])
    self.tester2 = np.array([[1, 0, 0, 4], [5, 6, 0, 8]])

  def test_norm_0(self):
    expected = np.array([5,2])
    result = norm_l0(self.tester1)
    np.testing.assert_equal(expected,result)
    
    expected = np.array([2, 3])
    result = norm_l0(self.tester2)
    np.testing.assert_equal(expected, result)

  def test_norm_l1(self):

    expected = np.array([15,12 ])
    result = norma_p(self.tester1,1)
    np.testing.assert_equal(expected, result)

    expected = np.array([5, 19])
    result = norma_p(self.tester2,1)
    np.testing.assert_equal(expected, result)

    
  def test_norm_l2(self):

    expected = np.array([ np.sqrt(55),np.sqrt(80) ])
    result = norma_p(self.tester1,2)
    np.testing.assert_equal(expected, result)

    expected = np.array([np.sqrt(17) ,np.sqrt(125)])
    result = norma_p(self.tester2,2)
    np.testing.assert_equal(expected, result)

  def test_norm_inf(self):
    a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
    expected = np.array([4, 8])
    result = vector_norm_inf(a)
    np.testing.assert_equal(expected, result)

In [ ]:
t = NormTestClass()

In [ ]:
# Norma 0
# Numeros de elementos diferentes a 0
def norm_l0(a):
  mask = a > 0
  return np.sum(mask,axis=1)

# Norma infinito
# El máximo
def n_inf(matriz):
  np.max(np.abs(matriz),axis=1)

# Norma p
def norma_p(matriz,p):
  return np.power( np.sum(np.power(np.abs(matriz),p),axis=1), 1/p)

# Ejercicio 2

Dada una matriz A con sus filas 1 y 2.

De cada fila calcular la norma l1 y l2.

Ordenar esa matriz en función de una norma creciente o decreciente. 

np.argsort()

Te devuelve un array con los valores del orden que ocupan los números en el orden

In [ ]:
a = np.array([[0,0],[3,4],[0,1]],dtype=np.float64)

In [ ]:
def sort_vector_by_norm_p(matrix,p,asc=True):
  '''
  a <numpy.array> Matrix to operate with
  n <int> Calculate norm n from norma_p 
  '''
  normal2 = norma_p(matrix,p=p)
  order = np.argsort(normal2 *-1)
  return matrix[order,:]

In [ ]:
mat = np.array([[1,2,3],[7,8,9],[4,5,6]],dtype=np.float64)
sort_vector_by_norm_p(mat,2)

array([[1., 2., 3.],
       [7., 8., 9.],
       [4., 5., 6.]])

In [ ]:
def sorting_vectors_by_norm_l2(matrix):
  norm_l2 = norma_p(matrix,p=2)
  arg_sort = np.argsort(norm_l2 * -1)
  return matrix[arg_sort, :]

In [ ]:
arg_sort = np.argsort(norma_p(mat,2) * -1)

# Ejercicio 3 

Muchas veces tenemos la bbdd sin una numeración "ordenada" de una matriz.
Quisiéramos crearles un índice que sí sea continuo, para poder acceder a los datos de una manera ordenada y prolija.


ej:

Tengo los nros de clientes [15 , 18 , 28 .. ]
y lo quiero pasa a [0,1,2... ] 


Quiero crear una clase que pase de identificador a index y de index a identificador. 

In [ ]:
users_id = np.array([15, 12, 14, 10, 1, 2, 1])
users_idx = np.array([0, 1, 2, 3, 4, 5, 4])


In [ ]:
unique_ids = np.unique(users_id)
unique_ids

array([ 1,  2, 10, 12, 14, 15])

In [ ]:
id2idx = np.ones(unique_ids.max()+1,dtype=np.int64) * -1
id2idx

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [ ]:
id2idx[unique_ids] = np.arange(unique_ids.size)
id2idx

array([-1,  0,  1, -1, -1, -1, -1, -1, -1, -1,  2, -1,  3, -1,  4,  5])

In [ ]:
id2idx[uni]

In [ ]:
class indexer():
  def __init__(self,ids):
    unique_ids = np.unique(ids)
    id2idx = np.ones(unique_ids.max()+1,dtype=np.int64) * -1
    id2idx[unique_ids] = np.arange(unique_ids.size)
    self.id2idx = id2idx
    self.idx2id = unique_ids

  def get_idxs(self,ids):
    ids = self.id2idx[ids]
    return ids, ids !=-1
  
  def get_ids(self,idxs):
    return self.idx2id[idxs]

In [ ]:
ind = indexer(users_id)

In [ ]:
ind.get_idxs(users_id)

(array([5, 3, 4, 2, 0, 1, 0]),
 array([ True,  True,  True,  True,  True,  True,  True]))

# Problema 4
## PRecision, recall y accuracy

True Positive (TP): la verdad es 1 y la producción es 1.

● True Negative (TN): la verdad es 0 y la predicción es 0.

● False Negative (FN): la verdad es 1 y la predicción es 0.

● False Positive (FP): la verdad es 0 y la producción es 1.

Se definen las siguientes métricas:

● Precision = TP / (TP + FP)

● Recall = TP / (TP + FN)

● Accuracy = (TP + TN) / (TP + TN + FP + FN)

Suponer que se tienen 2 arreglos:

truth = [1,1,0,1,1,1,0,0,0,1]

prediction = [1,1,1,1,0,0,1,1,0,0]

Calcular las 3 métricas con Numpy y operaciones vectorizadas.

In [ ]:
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

In [ ]:
rr = Precision(truth,prediction)

In [ ]:
rr()

0.5

In [ ]:
rr.truth
#https://www.protechtraining.com/content/python_fundamentals_tutorial-oop

array([1, 1, 0, 1, 1, 1, 0, 0, 0, 1])

In [ ]:
class ClassificationMetrics:
  def __init__(self,truth,prediction):
    self.prediction = prediction
    self.truth = truth
    self.lenght = len(truth)
    self.tp = (self.truth & self.prediction).sum() 
      
  def accuracy(self):
    tp_tn = np.equal(self.truth,self.prediction).sum()
    return tp_tn/self.lenght
  
  def recall(self):
    return self.tp/truth.sum() 
    # truth.sum() = TP + FN porque los TP son los positivos bien clasif,
    # los FN son POSITIVOS que fueron clasificados como Neg (False Negativos)
    # Por lo tanto TP+FN = All Real Positives = truth.sum()
  
  def precision(self): #TP / (TP + FP)
    tp_fp = self.prediction.sum()
    return self.tp/tp_fp



In [ ]:
classifier = ClassificationMetrics(truth,prediction)

In [ ]:
classifier.accuracy()

0.4

# Ejercicio 5
## Average quary precision

En information retrieval o search engine, en general contamos con queries “q” y para cada “q” una lista de
documentos que son verdaderamente relevantes. Para evaluar search engine, es común utilizar la métrica
average query precision. Dado un search engine y una lista de queries “q” para evaluación, podemos obtener
los siguientes resultados:

q_id = [1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]

predicted_rank = [0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3]

truth_relevance = [T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T ]

precision para q_id 1 = 2 / 4

precision para q_id 2 = 3 / 3

precision para q_id 3 = 0 / 5

precision para q_id 4 = 2 / 4

average query precision = ((2/4) + (3/3) + (0/5) + (2/4)) / 4

Calcular la métricas con Numpy y operaciones vectorizadas.

In [ ]:
q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])

predicted_rank = np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3])

trel = 'T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T'.replace(' ','').replace('T','1').replace('F','0').split(',')

truth_relevance = np.array([int(x) for x in trel])

In [ ]:
def avgQueryPrecision(queryids,predictedranks,realrelevance):
  uniqueids = np.unique(queryids)
  totalqueries = len(uniqueids)
  mask_dict = {}
  temp_wavg=0
  for i in uniqueids:
    mask = (queryids == i)
    nDocs = mask.sum()
    goodDocs = (mask & realrelevance).sum()
    temp_wavg += goodDocs / nDocs
  return temp_wavg / totalqueries

  

In [ ]:
avgQueryPrecision(q_id,predicted_rank,truth_relevance)

0.5

# Ejercicio 6
## Average query precision at K

En information retrieval o search engine, en general contamos con queries “q” y para cada “q” una lista de
documentos que son verdaderamente relevantes. Para evaluar search engine, es común utilizar la métrica
average query precision at K. Dado un search engine y una lista de queries “q” para evaluación, podemos
obtener los siguientes resultados:

k = 3

q_id = [1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]

predicted_rank = [0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3]

truth_relevance = [T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T ]

precision para q_id 1 = 2 / 3

precision para q_id 2 = 3 / 3

precision para q_id 3 = 0 / 3

precision para q_id 4 = 1 / 3

average query precision at K = ((2/3) + (3/3) + (0/3) + (1/3)) / 4

Calcular la métricas con Numpy y operaciones vectorizadas.

In [ ]:
q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])

predicted_rank = np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3])

trel = 'T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T'.replace(' ','').replace('T','1').replace('F','0').split(',')

truth_relevance = np.array([int(x) for x in trel])

In [ ]:
def avgQueryPrecision(queryids,predictedranks,realrelevance,k=3):
  '''
  '''
  mask_is_query = np.bincount(queryids) > 0 # Solo quedarse con vlaores de query que existan
  assert  np.all(np.bincount(queryids)[mask_is_query]>=k),'K demasiado grande para alguna query Id'

  uniqueids = np.unique(queryids)
  totalqueries = len(uniqueids)
  mask_dict = {}
  temp_wavg=0
  for i in uniqueids:
    mask = (queryids == i)
    goodDocs = (mask & realrelevance)[:3].sum()
    temp_wavg += goodDocs / k
  return temp_wavg / totalqueries

  

In [ ]:
avgQueryPrecision(q_id,predicted_rank,truth_relevance,k=3)

0.16666666666666666

# Ejercicio 7
## Computar las métrica con __call__

En problemas de machine learning, es muy común que para cada predicción que obtenemos en nuestro
dataset de verificacion y evaluacion, almacenemos en arreglos de numpy array el resultado de dicha
predicción, junto con el valor verdadero y parámetros auxiliares (como el ranking de la predicción y el query
id).

Luego de obtener todas las predicciones, podemos utilizar la información almacenada en los arreglos de
numpy, para calcular todas las métricas que queremos medir en nuestro sistema.

Una buena práctica para implementar esto en Python, es crear clases que hereden de una clase Metric
“base” y que cada métrica implemente el método __call__.

Utilizar herencia, operador __call__, kwargs, para escribir un programa que permita calcular todas las
métricas de los ejercicios anteriores mediante un for. Cual es la ventaja de resolver el problema utilizando
estas herramientas?

In [ ]:
class BaseMetric():
  def __init__(self,truth,prediction):
    self.prediction = prediction
    self.truth = truth
    self.lenght = len(truth)
    self.tp = (self.truth & self.prediction).sum() 
    self.tp_fp = prediction.sum()
    self.real_positive = truth.sum()
    self.tp_tn = np.equal(truth,prediction).sum()


class Precision(BaseMetric):
  def __call__(self):
    return self.tp / self.tp_fp

class recall(BaseMetric):
  def __call__(self):
    return self.tp/self.real_positive

class accuracy(BaseMetric):
  def __call__(self):
    return self.tp_tn/self.lenght

# Ejercicio 8
## Transformar un dataset a numpy estructurado con singleton

1) Desdegar un data set -- checked

2) Crear un array estructurado en numpy que represente la estructura del dataset 

3) Crear una clase que permita:
* Crear la estructura de un structured np array para el dataset
* Leer el csv, almacenar la información en el array precedente
* Guarlar el array estructurado en formato .pkl
* Crear una instancia singleton del array estrucyturado (usando __new__ e __init__ ) 
* Al crear la instancia, si se encuentra el .pkl carga desde el pkl. Si el .pkl no está, comenzar por transformar el .csv en .pkl y luego levantar la información.
* Optimizar usando los generators


-----------------------------

Note on numpy documentation

Users looking to manipulate tabular data, such as stored in csv files, may find other pydata projects more suitable, such as xarray, pandas, or DataArray. These provide a high-level interface for tabular data analysis and are better optimized for that use. For instance, the C-struct-like memory layout of structured arrays in numpy can lead to poor cache behavior in comparison.

## Punto 2 - Crear un array estructurado de numpy

Según la documentación de Kaggle se tienen 3 columnas:

1) userid: int

2) movieId: int

3) rating: float 


ejemplo

userid:1 | movieid:118 | rating 1.0

userid:1 | movieid:147 | rating 4.5


In [ ]:
type_structure = np.dtype([('userid',np.int),('movieid',np.int),('rating',np.float)])

In [ ]:
empty_rating_array = np.array([],dtype=type_structure)

In [ ]:
import os

In [ ]:
os.path.exists(datapath)

True

In [ ]:
from time import timestamp

ImportError: ignored

In [ ]:
os.path.isfile(datapath+'ratings.csv')

True

In [ ]:
import os
datapath = '/content/drive/My Drive/Especializacion UBA/Introduccion a IA/data/'
class StructuredNumpyArray(object):

  instance= None
  #type_structure = np.dtype([('userid',np.int),('movieid',np.int),('rating',np.float)])
  #empty_rating_array = np.array([],dtype=type_structure)

  def __new__(cls): #class method
    if StructuredNumpyArray.instance is None:
      print ('__new__ object created')
      StructuredNumpyArray.instance = super(StructuredNumpyArray,cls).__new__(cls)
      return StructuredNumpyArray.instance
    else:
      return StructuredNumpyArray.instance

  
  def __init__(self):
    self.structure = np.dtype([('userid',np.int),('movieid',np.int),('rating',np.float),('date',datetime)])
    self.structuredData = np.array([],dtype=self.structure)

    if os.path.isfile(datapath+'dataset.pkl'):
      self.structuredData = self.loadPickle(datapath+'dataset.pkl')

    else:
      self.structuredData = self.loadFromTxt(datapath+'ratings.csv',self.structure)
      self.savePickle()


  def savePickle(self):
    with open(datapath+'dataset.pkl','wb') as file:
      pk.dump(self.structuredData,file,protocol=pk.HIGHEST_PROTOCOL)


  @staticmethod
  def loadPickle(filetoopen):
    with open(filetoopen,'rb') as file:
      return pk.load(file)
      
  
  @staticmethod
  def loadFromTxt(pathtodata,structure):
    csv_structuredArray = np.genfromtxt(fname=pathtodata,dtype=structure,max_rows=500,delimiter=',',skip_header=True)
    return csv_structuredArray  
        


  

In [ ]:
mono = StructuredNumpyArray()

__new__ object created


In [ ]:
monito = StructuredNumpyArray()

NameError: ignored