In [242]:
import numpy as np
#import matplotlib.pyplot as plt

# XOR dataset

In [27]:
X = np.array([[[0,0]],[[0,1]],[[1,0]],[[1,1]]])
Y = np.array([[0,1,1,0]])

In [28]:
X[0].shape

(1, 2)

# Implementación

## Sigmoid

In [4]:
def sigmoid(x):
    '''
    Función sigmoid en el punto x.
    '''
    return 1 / (1+np.exp(-x))

def dsigmoid(x):
    '''
    Derivada de la función sigmoid en el punto x.
    '''
    return sigmoid(x)*(1-sigmoid(x))

In [231]:
np.random.uniform(-0.5,0.5,(2,2))

array([[ 0.35173509, -0.1404403 ],
       [ 0.40658401,  0.16219582]])

In [239]:
# Inicialización de parámetros

W1 = np.random.uniform(0.5,1,(2,2))
b1 = np.random.uniform(0.5,1,(2,1))
W2 = np.random.uniform(0.5,1,(1,2)) 
b2 = np.random.uniform(0.5,1,(1,1))


epochs = 300000
lr = 0.0025
error_list = []

for epoch in range(epochs):
    for i in range(4):
# Paso forward

        Z1 = W1 @ X[i].T + b1 # [2,1]
        A1 = sigmoid(Z1) #[2,1]

        Z2 = W2 @ A1 + b2 # [1,1]
        A2 = sigmoid(Z2) #[1,1]

        error = Y.T[i] - A2 #[1,1]
        error_list.append(error[0])

# Paso backwards
        
        #Output layer
        dJdW2 = -2*error*A1.T # [1,2]
        dJdb2 = -2*error*1 # float
        W2 = W2 - lr * dJdW2 # [1,2]
        b2 = b2 - lr * dJdb2 # [1,1]        
        
        #1st hidden layer
        dJdW1 = -2*error*W2.T*A1*(1-A1)*X[i].T
        dJdb1 = -2*error*W2.T*A1*(1-A1)*1
        W1 = W1 - lr * dJdW1 # [2,2]
        b1 = b1 - lr * dJdb1 #[2,1]


In [240]:
W1,b1,W2,b2

(array([[5.80478289, 5.76223053],
        [7.58278219, 7.67737846]]),
 array([[-8.85312194],
        [-3.51520535]]),
 array([[-14.65907458,  13.83099796]]),
 array([[-6.50287564]]))

In [241]:
for i in range(4):
    print(X[i],Y.T[i])
    print(sigmoid(W2@(W1 @ X[i].T+b1)+b2))

[[0 0]] [0]
[[1.]]
[[0 1]] [1]
[[1.]]
[[1 0]] [1]
[[1.]]
[[1 1]] [0]
[[1.]]
