In [2]:
import numpy as np
#import matplotlib.pyplot as plt

# XOR dataset

In [166]:
X = np.array([[[0,0]],[[0,1]],[[1,0]],[[1,1]]])
Y = np.array([[0,1,1,0]])

In [4]:
X[0].shape

(1, 2)

# Implementación

## Sigmoid

In [5]:
def sigmoid(x):
    '''
    Función sigmoid en el punto x.
    '''
    return 1 / (1+np.exp(-x))


In [171]:
# Inicialización de parámetros
np.random.seed(32)
W1 = np.random.uniform(-1,1,(2,2))*0.75
b1 = np.random.uniform(-1,1,(2,1))*0.75
W2 = np.random.uniform(-1,1,(1,2))*0.75
b2 = np.random.uniform(-1,1,(1,1))*0.75
# W1 = np.ones((2,2))
# b1 = np.ones((2,1))
# W2 = np.ones((1,2)) 
# b2 = np.ones((1,1))

epochs = 50000
lr = 0.15
error_list = []

for epoch in range(epochs):
    for i in range(4):
# Paso forward

        Z1 = W1 @ X[i].T + b1 # [2,1]
        A1 = sigmoid(Z1) #[2,1]

        Z2 = W2 @ A1 + b2 # [1,1]
        A2 = sigmoid(Z2) #[1,1]

        error = Y[0,i] - A2 #[1,1]
        error_list.append(error[0])

# Paso backwards
        dError = -2*error*A2*(1-A2)
    
        #Output layer
        dJdW2 = dError*A1.T # [1,2]
        dJdb2 = dError*1 # float
        W2 = W2 - lr * dJdW2 # [1,2]
        b2 = b2 - lr * dJdb2 # [1,1]        
        
        #1st hidden layer
        dJdW11 = dError*W2.T[0]*A1[0]*(1-A1[0])*X[i]
        dJdW12 = dError*W2.T[1]*A1[1]*(1-A1[1])*X[i]
        dJdb1 = dError*W2.T*A1*(1-A1)*1
        
        W1[0] = W1[0] - lr * dJdW11 # [2,2]
        W1[1] = W1[1] - lr * dJdW12
        b1 = b1 - lr * dJdb1 #[2,1]


In [172]:
for i in range(4):
    print(X[i],Y.T[i])
    print(sigmoid((W2@((W1 @ X[i].T) +b1))+b2))

[[0 0]] [0]
[[3.15957283e-12]]
[[0 1]] [1]
[[1.]]
[[1 0]] [1]
[[2.68451381e-11]]
[[1 1]] [0]
[[1.]]


# Otras pruebas


In [167]:
# Inicialización de parámetros
np.random.seed(30)
W1 = np.random.uniform(-1,1,(2,2))*0.5
b1 = np.random.uniform(-1,1,(2,1))*0.5
W2 = np.random.uniform(-1,1,(1,2))*0.5
b2 = np.random.uniform(-1,1,(1,1))*0.5
# W1 = np.ones((2,2))
# b1 = np.ones((2,1))
# W2 = np.ones((1,2)) 
# b2 = np.ones((1,1))


epochs = 30000
lr = 0.125
error_list = []

for epoch in range(epochs):
    for i in range(4):
# Paso forward

        Z1 = W1 @ X[i].T + b1 # [2,1]
        A1 = sigmoid(Z1) #[2,1]

        Z2 = W2 @ A1 + b2 # [1,1]
        A2 = sigmoid(Z2) #[1,1]

        error = Y[0,i] - A2 #[1,1]
        error_list.append(error[0])

# Paso backwards
        dError = -2*error
    
        #Output layer
        dJdW2 = dError*A1.T # [1,2]
        dJdb2 = dError*1 # float
        W2 = W2 - lr * dJdW2 # [1,2]
        b2 = b2 - lr * dJdb2 # [1,1]        
        
        #1st hidden layer
        dJdW11 = dError*W2[0,0]*A1[0]*(1-A1[0])*X[i]
        dJdW12 = dError*W2[0,1]*A1[1]*(1-A1[1])*X[i]
        dJdb1 = dError*W2.T*A1*(1-A1)*1
        
        W1[0] = W1[0] - lr * dJdW11# [2,2]
        W1[1] = W1[1] - lr * dJdW12
        b1 = b1 - lr * dJdb1 #[2,1]


In [168]:
for i in range(4):
    print(X[i],Y.T[i])
    print(sigmoid((W2@((W1 @ X[i].T) +b1))+b2))

[[0 0]] [0]
[[3.39483647e-28]]
[[0 1]] [1]
[[1.]]
[[1 0]] [1]
[[1.5377099e-35]]
[[1 1]] [0]
[[1.]]
