In [ ]:
import numpy as np

# Ejercicio 1

Dada una nube de puntos X y centros C, obtener las distancias de X a C.


In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
c = np.array([[1,0,0],[0,1,0]])

In [ ]:
expanded_c = c[:,None]

In [ ]:
c[:,None].shape

(2, 1, 3)

In [ ]:
distances = np.sqrt(np.sum((expanded_c-x)**2,axis=2))

In [ ]:
distances

array([[ 3.60555128,  8.36660027, 13.45362405],
       [ 3.31662479,  8.24621125, 13.37908816]])

In [ ]:
print(c,c.shape)
print(expanded_c,expanded_c.shape )
print(expanded_c[0],expanded_c[0].shape)
print(expanded_c[0][0],expanded_c[0][0].shape)
print(expanded_c[0][0][0])

[[1 0 0]
 [0 1 0]] (2, 3)
[[[1 0 0]]

 [[0 1 0]]] (2, 1, 3)
[[1 0 0]] (1, 3)
[1 0 0] (3,)
1


In [ ]:
np.sum((x - expanded_c)**2,axis=0)

array([[  1,   5,  18],
       [ 25,  41,  72],
       [ 85, 113, 162]])

In [ ]:
(x - expanded_c)**2

array([[[ 0,  4,  9],
        [ 9, 25, 36],
        [36, 64, 81]],

       [[ 1,  1,  9],
        [16, 16, 36],
        [49, 49, 81]]])

# Ejercicio 2

Obtener para cada fila de X el índice de la fila en C con distancia euclídea más pequeña.

Es decir, para fila en X a qué cluster pertenece de C.

In [ ]:
distances

array([[ 3.60555128,  8.36660027, 13.45362405],
       [ 3.31662479,  8.24621125, 13.37908816]])

In [ ]:
cluster = np.argmin(distances,axis=0)

In [ ]:
cluster

array([1, 1, 1])

# Ejercicio 3
K-means es uno de los algoritmos más básicos en Machine Learning no supervisado.
Es un algoritmo de clusterización, que agrupa los datos que comparten características similares.
Recordemos que entendemos datos como n realizaciones del vector aleatorio X.
El algoritmo K-means funcione de la siguiente manera:
1. El usuario selecciona la cantidad de clusters a crear (n).
2. Se seleccionan n elementos aleatorios de X como posiciones iniciales del los centroides C.
3. Se calcula la distancia entre todos los puntos en X y todos los puntos en C.
4. Para cada punto en X se selecciona el centroide más cercano de C.
5. Se recalculan los centroides C a partir de usar las filas de X que pertenecen a cada centroide.
6. Se itera entre 3 y 5 una cantidad fija de veces o hasta que la posición de los centroides no cambie.
Implementar la función def k_means(X, n) de manera tal que al finalizar devuelva la posición de los
centroides y a que cluster pertenece cada fila de X.
Hint: para (2) utilizar funciones de np.random, para (3) y (4) usar los ejercicios anteriores,
para (5) es válido utilizar un for. Iterar 10 veces entre (3) y (5).


In [ ]:
import numpy as np

In [ ]:
x = np.random.randint(low=0,high=100,size=(1000,3))

In [ ]:
def kmeans(x,nclus,max_iter=2):

  random_index = np.random.randint(low=0,high=max(x.shape),size=nclus) # Vector random auxiliar
  centroids = np.array(x[random_index]) # Inicializa centroides random
  print(centroids.shape[0])
  expanded_centroids = centroids[:,None] # Matriz expandida para poder broadcastear abajo
  
  for k in range(max_iter): # Maximas iteraciones hardcodeadas
    for i in range(centroids.shape[0]): # Actualizo CADA centroide
      distances = np.sqrt(np.sum( (expanded_centroids-x)**2,axis=2)) # Calculo de distancias entre vectores y los centroides
      arg_min = np.argmin(distances,axis=0) # Asigna Cluster a cada Vector de X
      centroids[i] = np.mean(x[arg_min == i, :], axis=0) 
      # Calcula nuevo centroide como el promedio de los asignados en la iteración anterior

  return centroids, arg_min

# Ejercicio 4 Dataset sintético

* Definir una matriz con centroides [1,0,0,0] y [0,1,0,0]
*Utilizar una constante para separar o alejar los centroides entre si.
* Utilizar np.repeat para crear n/2 muestras de cada centroide.
*Sumar a cada centroide un vector aleatorio normal i.i.d. con media 0 y desvio (np.random.normal).
* Armar un arreglo que tenga n enteros indicado si la muestra pertenece a A o a B.

In [ ]:
def dataset(n_samples):
  centroids = np.array([[1,0,0,0],[0,1,0,0]])
  long_centroids = centroids * np.random.randint(low=1,high=10,size=(2,1))
  moved_long_centroids = np.repeat(centroids,n_samples/2,axis=0) 
  noise = np.random.normal(size=(n_samples,centroids.shape[1]))
  data = moved_long_centroids + noise
  cluster_ids = np.array([[0],[1]])
  cluster_ids = np.repeat(cluster_ids,n_samples/2,axis=0)
  return data, cluster_ids


# Ejercicio 5
Simular una exponencial de parámetro lambda

In [ ]:
def expo_from_uni(n,lam):
  x_uni = np.random.uniform(size=(n,1))
  x_exp = -np.log(1-x_uni)/lam
  return x_exp

In [ ]:
expo_from_uni(2,4)

array([[0.58876861],
       [0.27591633]])

# Ejercicio 6 - Calcular inversa generalizada de f(x) = 3x**2


Si la pdf  3x2 entonces la CDF es la integral, que da x3, cuya inversa es potencia(1/3)


In [ ]:
def simulacion_3x2(n):
  '''
  Muestrea la pdf = 3x^2 x en [0,1] a
  travès del método de inversa generalizada.
  '''
  x_uni = np.random.uniform(size=(n,1))
  chosen_x = np.power(x_uni,1/3)
  return chosen_x

 # Ejercicio 7
Dado un dataset X de n muestras y m columnas, implementar un método en numpy para normalizar con
z-score. Pueden utilizar np.mean() y np.std()


In [ ]:
a = np.array([[1,1,1,1],[1,2,3,4],[1,6,7,8],[1,10,11,12]])

In [ ]:
def normalizer(x):
  means = np.mean(x,axis=0) #Calcula las medias por columna
  stds  = np.std(x,axis=0) # Calcula las std dev por columna
  return (x-means)/stds

# Ejercicio 8

Dado un dataset X calcular PCA para reducir dimensión.
Siguiendo los pasos del slide anterior, se requiere utilizar numpy para calcular PCA del dataset de entrada X
utilizando las 2 componentes más importantes.
x = np.array([ [0.4, 4800, 5.5], [0.7, 12104, 5.2], [1, 12500, 5.5], [1.5, 7002, 4.0] ])
Al finalizar la implementación en numpy corroborar obtener los mismos resultados que utilizando el código
de la librería scikit-learn. Para comparar las matrices escribir un tests usando np.testing.assert_allclose

In [ ]:
x = np.array([ [0.4, 4800, 5.5], [0.7, 12104, 5.2], [1, 12500, 5.5], [1.5, 7002, 4.0] ])

In [ ]:
def pca_casero(dataset,d):
  x_means = np.mean(dataset,axis=0) # Toma medias por columnas
  centered_dataset = dataset - x_means # Mueve al centro
  cov = np.cov(np.transpose(centered_dataset)) # Covariance matrix
  eigValues,eigVectores =  np.linalg.eig(cov)
  eigValuesOrder = np.argsort(np.abs(eigValues))
## incorporar lo del valor absoluto para los autovalores

  eigVectores = eigVectores[eigValuesOrder[::-1]]
  pca = np.matmul(dataset,eigVectores[:,:d])
  return pca

In [ ]:
pca_casero(x,2)

array([[ 5.74825533e+00, -2.62826180e+03],
       [ 5.82601272e+00, -6.62734221e+03],
       [ 6.14649766e+00, -6.84439725e+03],
       [ 4.36215576e+00, -3.83474400e+03]])

# Ejercicio 9 - Remover filas y columnas con Nan de un dataset

Dado un dataset, hacer una función que filtre columnas y filas que tienen nan.

In [ ]:
a = np.array([[1,2,3,4,5,6,7,8,9],
              [1,np.nan,2,4,5,6,np.nan,4,1],
              [3,6,4,np.nan,2,1,5,6,7]])

In [ ]:
def desnanizador(x):
  '''
  Desdenanizador recibe un dataset en formato np.array y 
  le quita todas las filas y columnas que tengan nans.
  No es lo más óptimo, pero es para practicar numpy.

  Prefiere eliminar primero un registro antes que eliminar una variable
  Podrìan verse variantes.
  '''
  row_filter =  np.logical_not(np.any(np.isnan(x) ,axis=1))
  x = x[row_filter,:]
  column_filter =  np.logical_not(np.any(np.isnan(x) ,axis=0))
  x = x[:,column_filter]
  print(x)

  return x

In [ ]:
np.mean(a,axis=0)

array([1.66666667,        nan, 3.        ,        nan, 4.        ,
       4.33333333,        nan, 6.        , 5.66666667])

# Ejercicio 10 Reemplazar Nans por la media de la columna

In [ ]:
a.shape[1]

9

In [ ]:
a

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1., nan,  2.,  4.,  5.,  6., nan,  4.,  1.],
       [ 3.,  6.,  4., nan,  2.,  1.,  5.,  6.,  7.]])

In [ ]:
for x in np.where(np.any(np.isnan(a),axis=0))[0]:
  print(x)

1
3
6


In [ ]:
a[:,[1]] = 5

In [ ]:
a

array([[ 1.,  5.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  5.,  2.,  4.,  5.,  6., nan,  4.,  1.],
       [ 3.,  5.,  4., nan,  2.,  1.,  5.,  6.,  7.]])

In [ ]:
def desnanizador_promedio(x):
'''
Desnaniza reemplazando por el promedio de la columna.
Si hubiera una columna con todos nan, rompe. 
'''

  columnas_con_nans = np.where(np.any(np.isnan(x),axis=0))[0] # Genera indices de columnas con nan
  for i in columnas_con_nans: #Loop sobre ese índice
    x_i = x[:,[i]] #Toma prestada una columna con nan
    x_i = x_i[np.logical_not(np.isnan(x_i))] # Le quita los nan a esa columna
    media = np.mean(x_i) #Calcula la media de la columna sin los nans
    x[:,[i]] = np.nan_to_num(x[:,[i]],nan=media) #Reemplaza nan en la columna de X original
  return x #Devuelve el dataset limpio

In [ ]:
desnanizador_promedio(a)

array([[1., 5., 3., 4., 5., 6., 7., 8., 9.],
       [1., 5., 2., 4., 5., 6., 6., 4., 1.],
       [3., 5., 4., 4., 2., 1., 5., 6., 7.]])

#Ejercicio 11: Train, validation, test

Hacer un random split en 70-20-10

In [ ]:
def train_test_validation_split(x):
  registros = len(x) # Cantidad de registros
  x = np.random.permutation(x) # Permuta el dataset
  trains = int(np.floor(0.70*registros)) # Calcula el corte para 70%
  test = int(np.floor(0.20*registros)) #idem
  validation = int(np.floor(0.10*registros)) #idem
  x_train = x[0:trains,:] #toma el primero 70% de los registros permutados
  x_test = x[trains:test,:] #idem 20&
  x_validation = x[test:,:] #idem 10&
  return x_train,x_test,x_validation #devuelve los 3 splits

In [ ]:
random_data = np.random.randint(low=0,high=25,size=(1000,10))

In [ ]:
a,b,c= train_test_validation_split(random_data)

In [ ]:
a,b,c

(array([[14, 23,  5, ..., 16,  8, 15],
        [20,  1,  0, ..., 12, 12, 21],
        [ 3,  6,  6, ...,  7,  0, 12],
        ...,
        [17, 22, 22, ..., 24, 19, 20],
        [14,  0, 12, ...,  9, 23, 24],
        [15, 16, 23, ..., 17,  3, 18]]),
 array([], shape=(0, 10), dtype=int64),
 array([[ 9, 24,  2, ..., 10,  3, 13],
        [ 2, 11,  9, ..., 16,  1,  4],
        [ 8, 14, 14, ...,  7,  4,  8],
        ...,
        [ 1, 22,  4, ..., 22,  6,  5],
        [ 9, 13,  2, ...,  2,  8, 11],
        [ 2, 14,  4, ..., 22, 13, 22]]))

#Ejercicio 12 - Integrador